### Each video  = sum of frames
### Each frame = collection of pixel , each pixel has a location in the picture or frame and an associated value depicting intensity of color of that specefic channel.

In [1]:
#import our dependencies
import cv2
import numpy as np

In [2]:
img = cv2.imread('img.jpg',cv2.IMREAD_COLOR)

In [4]:
# To refer to a particular pixel use something like this
px = img[35,35]

In [5]:
#to change the value of a particular pixel
img[25,25] = [255,255,255]

In [8]:
# We can refer to the region of an image as :
region = img[20:500,50:800]

print(region)

[[[ 1  3  4]
  [ 5  8 12]
  [13 16 20]
  ..., 
  [17 28 26]
  [17 28 26]
  [16 27 25]]

 [[ 3  5  6]
  [ 7 10 14]
  [15 18 22]
  ..., 
  [17 28 26]
  [17 28 26]
  [16 27 25]]

 [[ 4  6  7]
  [ 9 12 16]
  [17 20 24]
  ..., 
  [17 28 26]
  [17 28 26]
  [16 27 25]]

 ..., 
 [[ 5  4  0]
  [ 5  4  0]
  [ 5  4  0]
  ..., 
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 5  4  0]
  [ 5  4  0]
  [ 5  4  0]
  ..., 
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]

 [[ 5  4  0]
  [ 5  4  0]
  [ 5  4  0]
  ..., 
  [ 2  2  2]
  [ 2  2  2]
  [ 2  2  2]]]


In [10]:
region = [255,255,255]
print(img.size)
print(img.shape)
print(img.dtype)

1226880
(480, 852, 3)
uint8


In [11]:
t = img[100:250,200:500] 
img[200:350,100:400] = t
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()